<?php namespace RainLab\User\Updates;

use October\Rain\Database\Updates\Seeder;
use RainLab\User\Models\Country;

class AddUkCounties extends Seeder
{

    public function run()
    {
        $uk = Country::whereCode('GB')->first();
        $uk->states()->createMany([
            ["name"=>"Aberdeenshire",     "code"=>"ABE"],
            ["name"=>"Anglesey",          "code"=>"ALY"],
            ["name"=>"Angus",             "code"=>"ANG"],
            ["name"=>"Argyll",            "code"=>"ARG"],
            ["name"=>"Ayrshire",          "code"=>"AYR"],
            ["name"=>"Banffshire",        "code"=>"BAN"],
            ["name"=>"Bedfordshire",      "code"=>"BED"],
            ["name"=>"Berkshire",         "code"=>"BER"],
            ["name"=>"Berwickshire",      "code"=>"BWS"],
            ["name"=>"Brecknockshire",    "code"=>"BRE"],
            ["name"=>"Buckinghamshire",   "code"=>"BUC"],
            ["name"=>"Bute",              "code"=>"BUT"],
            ["name"=>"Caernarfonshire",   "code"=>"CAE"],
            ["name"=>"Caithness",         "code"=>"CAI"],
            ["name"=>"Cambridgeshire",    "code"=>"CAM"],
            ["name"=>"Cardiganshire",     "code"=>"CAR"],
            ["name"=>"Carmarthenshire",   "code"=>"CMS"],
            ["name"=>"Cheshire",          "code"=>"CHE"],
            ["name"=>"Clackmannanshire",  "code"=>"CLA"],
            ["name"=>"Cleveland",         "code"=>"CLE"],
            ["name"=>"Cornwall",          "code"=>"COR"],
            ["name"=>"Cromartyshire",     "code"=>"CRO"],
            ["name"=>"Cumberland",        "code"=>"CBR"],
            ["name"=>"Cumbria",           "code"=>"CUM"],
            ["name"=>"Denbighshire",      "code"=>"DEN"],
            ["name"=>"Derbyshire",        "code"=>"DER"],
            ["name"=>"Devon",             "code"=>"DEV"],
            ["name"=>"Dorset",            "code"=>"DOR"],
            ["name"=>"Dumbartonshire",    "code"=>"DBS"],
            ["name"=>"Dumfriesshire",     "code"=>"DUM"],
            ["name"=>"Durham",            "code"=>"DUR"],
            ["name"=>"East Lothian",      "code"=>"ELO"],
            ["name"=>"Essex",             "code"=>"ESS"],
            ["name"=>"Flintshire",        "code"=>"FLI"],
            ["name"=>"Fife",              "code"=>"FIF"],
            ["name"=>"Glamorgan",         "code"=>"GLA"],
            ["name"=>"Gloucestershire",   "code"=>"GLO"],
            ["name"=>"Hampshire",         "code"=>"HAM"],
            ["name"=>"Herefordshire",     "code"=>"HER"],
            ["name"=>"Hertfordshire",     "code"=>"HTF"],
            ["name"=>"Huntingdonshire",   "code"=>"HUN"],
            ["name"=>"Inverness",         "code"=>"INV"],
            ["name"=>"Kent",              "code"=>"KEN"],
            ["name"=>"Kincardineshire",   "code"=>"KCD"],
            ["name"=>"Kinross-shire",     "code"=>"KIN"],
            ["name"=>"Kirkcudbrightshire","code"=>"KIR"],
            ["name"=>"Lanarkshire",       "code"=>"LKS"],
            ["name"=>"Lancashire",        "code"=>"LAN"],
            ["name"=>"Leicestershire",    "code"=>"LEI"],
            ["name"=>"Lincolnshire",      "code"=>"LIN"],
            ["name"=>"London",            "code"=>"LON"],
            ["name"=>"Manchester",        "code"=>"MAN"],
            ["name"=>"Merionethshire",    "code"=>"MER"],
            ["name"=>"Merseyside",        "code"=>"MER"],
            ["name"=>"Middlesex",         "code"=>"MDX"],
            ["name"=>"Midlands",          "code"=>"MID"],
            ["name"=>"Midlothian",        "code"=>"MLT"],
            ["name"=>"Monmouthshire",     "code"=>"MON"],
            ["name"=>"Montgomeryshire",   "code"=>"MGY"],
            ["name"=>"Moray",             "code"=>"MOR"],
            ["name"=>"Nairnshire",        "code"=>"NAI"],
            ["name"=>"Norfolk",           "code"=>"NOR"],
            ["name"=>"Northamptonshire",  "code"=>"NMP"],
            ["name"=>"Northumberland",    "code"=>"NUM"],
            ["name"=>"Nottinghamshire",   "code"=>"NOT"],
            ["name"=>"Orkney",            "code"=>"ORK"],
            ["name"=>"Oxfordshire",       "code"=>"OXF"],
            ["name"=>"Peebleshire",       "code"=>"PEE"],
            ["name"=>"Pembrokeshire",     "code"=>"PEM"],
            ["name"=>"Perthshire",        "code"=>"PER"],
            ["name"=>"Radnorshire",       "code"=>"RAD"],
            ["name"=>"Renfrewshire",      "code"=>"REN"],
            ["name"=>"Ross & Cromarty",   "code"=>"ROS"],
            ["name"=>"Roxburghshire",     "code"=>"ROX"],
            ["name"=>"Rutland",           "code"=>"RUT"],
            ["name"=>"Selkirkshire",      "code"=>"SEL"],
            ["name"=>"Shetland",          "code"=>"SHE"],
            ["name"=>"Shropshire",        "code"=>"SHR"],
            ["name"=>"Somerset",          "code"=>"SOM"],
            ["name"=>"Staffordshire",     "code"=>"STA"],
            ["name"=>"Stirlingshire",     "code"=>"STI"],
            ["name"=>"Suffolk",           "code"=>"SUF"],
            ["name"=>"Surrey",            "code"=>"SUR"],
            ["name"=>"Sussex",            "code"=>"SUS"],
            ["name"=>"Sutherland",        "code"=>"SUT"],
            ["name"=>"Tyne & Wear",       "code"=>"TYN"],
            ["name"=>"Warwickshire",      "code"=>"WAR"],
            ["name"=>"West Lothian",      "code"=>"WLO"],
            ["name"=>"Westmorland",       "code"=>"WES"],
            ["name"=>"Wigtownshire",      "code"=>"WIG"],
            ["name"=>"Wiltshire",         "code"=>"WIL"],
            ["name"=>"Worcestershire",    "code"=>"WOR"],
            ["name"=>"Yorkshire",         "code"=>"YOR"]
        ]);

    }

}