<?php namespace RainLab\User\Updates;

use October\Rain\Database\Updates\Seeder;
use RainLab\User\Models\Country;
use RainLab\User\Models\State;

class SeedAllTables extends Seeder
{

    public function run()
    {
        Country::insert([
            ['enabled' => true, 'code' => 'US', 'name' => 'United States'],
            ['enabled' => true, 'code' => 'CA', 'name' => 'Canada'],
            ['enabled' => true, 'code' => 'AU', 'name' => 'Australia'],
            ['enabled' => false, 'code' => 'FR', 'name' => 'France'],
            ['enabled' => false, 'code' => 'DE', 'name' => 'Germany'],
            ['enabled' => false, 'code' => 'IS', 'name' => 'Iceland'],
            ['enabled' => false, 'code' => 'IE', 'name' => 'Ireland'],
            ['enabled' => false, 'code' => 'IT', 'name' => 'Italy'],
            ['enabled' => false, 'code' => 'ES', 'name' => 'Spain'],
            ['enabled' => false, 'code' => 'SE', 'name' => 'Sweden'],
            ['enabled' => false, 'code' => 'AT', 'name' => 'Austria'],
            ['enabled' => false, 'code' => 'BE', 'name' => 'Belgium'],
            ['enabled' => false, 'code' => 'FI', 'name' => 'Finland'],
            ['enabled' => false, 'code' => 'CZ', 'name' => 'Czech Republic'],
            ['enabled' => false, 'code' => 'DK', 'name' => 'Denmark'],
            ['enabled' => false, 'code' => 'NO', 'name' => 'Norway'],
            ['enabled' => false, 'code' => 'GB', 'name' => 'United Kingdom'],
            ['enabled' => false, 'code' => 'CH', 'name' => 'Switzerland'],
            ['enabled' => false, 'code' => 'NZ', 'name' => 'New Zealand'],
            ['enabled' => false, 'code' => 'RU', 'name' => 'Russian Federation'],
            ['enabled' => false, 'code' => 'PT', 'name' => 'Portugal'],
            ['enabled' => false, 'code' => 'NL', 'name' => 'Netherlands'],
            ['enabled' => false, 'code' => 'IM', 'name' => 'Isle of Man'],
            ['enabled' => false, 'code' => 'AF', 'name' => 'Afghanistan'],
            ['enabled' => false, 'code' => 'AX', 'name' => 'Aland Islands '],
            ['enabled' => false, 'code' => 'AL', 'name' => 'Albania'],
            ['enabled' => false, 'code' => 'DZ', 'name' => 'Algeria'],
            ['enabled' => false, 'code' => 'AS', 'name' => 'American Samoa'],
            ['enabled' => false, 'code' => 'AD', 'name' => 'Andorra'],
            ['enabled' => false, 'code' => 'AO', 'name' => 'Angola'],
            ['enabled' => false, 'code' => 'AI', 'name' => 'Anguilla'],
            ['enabled' => false, 'code' => 'AQ', 'name' => 'Antarctica'],
            ['enabled' => false, 'code' => 'AG', 'name' => 'Antigua and Barbuda'],
            ['enabled' => false, 'code' => 'AR', 'name' => 'Argentina'],
            ['enabled' => false, 'code' => 'AM', 'name' => 'Armenia'],
            ['enabled' => false, 'code' => 'AW', 'name' => 'Aruba'],
            ['enabled' => false, 'code' => 'AZ', 'name' => 'Azerbaijan'],
            ['enabled' => false, 'code' => 'BS', 'name' => 'Bahamas'],
            ['enabled' => false, 'code' => 'BH', 'name' => 'Bahrain'],
            ['enabled' => false, 'code' => 'BD', 'name' => 'Bangladesh'],
            ['enabled' => false, 'code' => 'BB', 'name' => 'Barbados'],
            ['enabled' => false, 'code' => 'BY', 'name' => 'Belarus'],
            ['enabled' => false, 'code' => 'BZ', 'name' => 'Belize'],
            ['enabled' => false, 'code' => 'BJ', 'name' => 'Benin'],
            ['enabled' => false, 'code' => 'BM', 'name' => 'Bermuda'],
            ['enabled' => false, 'code' => 'BT', 'name' => 'Bhutan'],
            ['enabled' => false, 'code' => 'BO', 'name' => 'Bolivia, Plurinational State of'],
            ['enabled' => false, 'code' => 'BQ', 'name' => 'Bonaire, Sint Eustatius and Saba'],
            ['enabled' => false, 'code' => 'BA', 'name' => 'Bosnia and Herzegovina'],
            ['enabled' => false, 'code' => 'BW', 'name' => 'Botswana'],
            ['enabled' => false, 'code' => 'BV', 'name' => 'Bouvet Island'],
            ['enabled' => false, 'code' => 'BR', 'name' => 'Brazil'],
            ['enabled' => false, 'code' => 'IO', 'name' => 'British Indian Ocean Territory'],
            ['enabled' => false, 'code' => 'BN', 'name' => 'Brunei Darussalam'],
            ['enabled' => false, 'code' => 'BG', 'name' => 'Bulgaria'],
            ['enabled' => false, 'code' => 'BF', 'name' => 'Burkina Faso'],
            ['enabled' => false, 'code' => 'BI', 'name' => 'Burundi'],
            ['enabled' => false, 'code' => 'KH', 'name' => 'Cambodia'],
            ['enabled' => false, 'code' => 'CM', 'name' => 'Cameroon'],
            ['enabled' => false, 'code' => 'CV', 'name' => 'Cape Verde'],
            ['enabled' => false, 'code' => 'KY', 'name' => 'Cayman Islands'],
            ['enabled' => false, 'code' => 'CF', 'name' => 'Central African Republic'],
            ['enabled' => false, 'code' => 'TD', 'name' => 'Chad'],
            ['enabled' => false, 'code' => 'CL', 'name' => 'Chile'],
            ['enabled' => false, 'code' => 'CN', 'name' => 'China'],
            ['enabled' => false, 'code' => 'CX', 'name' => 'Christmas Island'],
            ['enabled' => false, 'code' => 'CC', 'name' => 'Cocos (Keeling) Islands'],
            ['enabled' => false, 'code' => 'CO', 'name' => 'Colombia'],
            ['enabled' => false, 'code' => 'KM', 'name' => 'Comoros'],
            ['enabled' => false, 'code' => 'CG', 'name' => 'Congo'],
            ['enabled' => false, 'code' => 'CD', 'name' => 'Congo, the Democratic Republic of the'],
            ['enabled' => false, 'code' => 'CK', 'name' => 'Cook Islands'],
            ['enabled' => false, 'code' => 'CR', 'name' => 'Costa Rica'],
            ['enabled' => false, 'code' => 'CI', 'name' => 'Cote d\'Ivoire'],
            ['enabled' => false, 'code' => 'HR', 'name' => 'Croatia'],
            ['enabled' => false, 'code' => 'CU', 'name' => 'Cuba'],
            ['enabled' => false, 'code' => 'CW', 'name' => 'Curaçao'],
            ['enabled' => false, 'code' => 'CY', 'name' => 'Cyprus'],
            ['enabled' => false, 'code' => 'DJ', 'name' => 'Djibouti'],
            ['enabled' => false, 'code' => 'DM', 'name' => 'Dominica'],
            ['enabled' => false, 'code' => 'DO', 'name' => 'Dominican Republic'],
            ['enabled' => false, 'code' => 'EC', 'name' => 'Ecuador'],
            ['enabled' => false, 'code' => 'EG', 'name' => 'Egypt'],
            ['enabled' => false, 'code' => 'SV', 'name' => 'El Salvador'],
            ['enabled' => false, 'code' => 'GQ', 'name' => 'Equatorial Guinea'],
            ['enabled' => false, 'code' => 'ER', 'name' => 'Eritrea'],
            ['enabled' => false, 'code' => 'EE', 'name' => 'Estonia'],
            ['enabled' => false, 'code' => 'ET', 'name' => 'Ethiopia'],
            ['enabled' => false, 'code' => 'FK', 'name' => 'Falkland Islands (Malvinas)'],
            ['enabled' => false, 'code' => 'FO', 'name' => 'Faroe Islands'],
            ['enabled' => false, 'code' => 'FJ', 'name' => 'Fiji'],
            ['enabled' => false, 'code' => 'GF', 'name' => 'French Guiana'],
            ['enabled' => false, 'code' => 'PF', 'name' => 'French Polynesia'],
            ['enabled' => false, 'code' => 'TF', 'name' => 'French Southern Territories'],
            ['enabled' => false, 'code' => 'GA', 'name' => 'Gabon'],
            ['enabled' => false, 'code' => 'GM', 'name' => 'Gambia'],
            ['enabled' => false, 'code' => 'GE', 'name' => 'Georgia'],
            ['enabled' => false, 'code' => 'GH', 'name' => 'Ghana'],
            ['enabled' => false, 'code' => 'GI', 'name' => 'Gibraltar'],
            ['enabled' => false, 'code' => 'GR', 'name' => 'Greece'],
            ['enabled' => false, 'code' => 'GL', 'name' => 'Greenland'],
            ['enabled' => false, 'code' => 'GD', 'name' => 'Grenada'],
            ['enabled' => false, 'code' => 'GP', 'name' => 'Guadeloupe'],
            ['enabled' => false, 'code' => 'GU', 'name' => 'Guam'],
            ['enabled' => false, 'code' => 'GT', 'name' => 'Guatemala'],
            ['enabled' => false, 'code' => 'GG', 'name' => 'Guernsey'],
            ['enabled' => false, 'code' => 'GN', 'name' => 'Guinea'],
            ['enabled' => false, 'code' => 'GW', 'name' => 'Guinea-Bissau'],
            ['enabled' => false, 'code' => 'GY', 'name' => 'Guyana'],
            ['enabled' => false, 'code' => 'HT', 'name' => 'Haiti'],
            ['enabled' => false, 'code' => 'HM', 'name' => 'Heard Island and McDonald Islands'],
            ['enabled' => false, 'code' => 'VA', 'name' => 'Holy See (Vatican City State)'],
            ['enabled' => false, 'code' => 'HN', 'name' => 'Honduras'],
            ['enabled' => false, 'code' => 'HK', 'name' => 'Hong Kong'],
            ['enabled' => false, 'code' => 'HU', 'name' => 'Hungary'],
            ['enabled' => false, 'code' => 'IN', 'name' => 'India'],
            ['enabled' => false, 'code' => 'ID', 'name' => 'Indonesia'],
            ['enabled' => false, 'code' => 'IR', 'name' => 'Iran, Islamic Republic of'],
            ['enabled' => false, 'code' => 'IQ', 'name' => 'Iraq'],
            ['enabled' => false, 'code' => 'IL', 'name' => 'Israel'],
            ['enabled' => false, 'code' => 'JM', 'name' => 'Jamaica'],
            ['enabled' => false, 'code' => 'JP', 'name' => 'Japan'],
            ['enabled' => false, 'code' => 'JE', 'name' => 'Jersey'],
            ['enabled' => false, 'code' => 'JO', 'name' => 'Jordan'],
            ['enabled' => false, 'code' => 'KZ', 'name' => 'Kazakhstan'],
            ['enabled' => false, 'code' => 'KE', 'name' => 'Kenya'],
            ['enabled' => false, 'code' => 'KI', 'name' => 'Kiribati'],
            ['enabled' => false, 'code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of'],
            ['enabled' => false, 'code' => 'KR', 'name' => 'Korea, Republic of'],
            ['enabled' => false, 'code' => 'KW', 'name' => 'Kuwait'],
            ['enabled' => false, 'code' => 'KG', 'name' => 'Kyrgyzstan'],
            ['enabled' => false, 'code' => 'LA', 'name' => 'Lao People\'s Democratic Republic'],
            ['enabled' => false, 'code' => 'LV', 'name' => 'Latvia'],
            ['enabled' => false, 'code' => 'LB', 'name' => 'Lebanon'],
            ['enabled' => false, 'code' => 'LS', 'name' => 'Lesotho'],
            ['enabled' => false, 'code' => 'LR', 'name' => 'Liberia'],
            ['enabled' => false, 'code' => 'LY', 'name' => 'Libyan Arab Jamahiriya'],
            ['enabled' => false, 'code' => 'LI', 'name' => 'Liechtenstein'],
            ['enabled' => false, 'code' => 'LT', 'name' => 'Lithuania'],
            ['enabled' => false, 'code' => 'LU', 'name' => 'Luxembourg'],
            ['enabled' => false, 'code' => 'MO', 'name' => 'Macao'],
            ['enabled' => false, 'code' => 'MK', 'name' => 'Macedonia'],
            ['enabled' => false, 'code' => 'MG', 'name' => 'Madagascar'],
            ['enabled' => false, 'code' => 'MW', 'name' => 'Malawi'],
            ['enabled' => false, 'code' => 'MY', 'name' => 'Malaysia'],
            ['enabled' => false, 'code' => 'MV', 'name' => 'Maldives'],
            ['enabled' => false, 'code' => 'ML', 'name' => 'Mali'],
            ['enabled' => false, 'code' => 'MT', 'name' => 'Malta'],
            ['enabled' => false, 'code' => 'MH', 'name' => 'Marshall Islands'],
            ['enabled' => false, 'code' => 'MQ', 'name' => 'Martinique'],
            ['enabled' => false, 'code' => 'MR', 'name' => 'Mauritania'],
            ['enabled' => false, 'code' => 'MU', 'name' => 'Mauritius'],
            ['enabled' => false, 'code' => 'YT', 'name' => 'Mayotte'],
            ['enabled' => false, 'code' => 'MX', 'name' => 'Mexico'],
            ['enabled' => false, 'code' => 'FM', 'name' => 'Micronesia, Federated States of'],
            ['enabled' => false, 'code' => 'MD', 'name' => 'Moldova, Republic of'],
            ['enabled' => false, 'code' => 'MC', 'name' => 'Monaco'],
            ['enabled' => false, 'code' => 'MN', 'name' => 'Mongolia'],
            ['enabled' => false, 'code' => 'ME', 'name' => 'Montenegro'],
            ['enabled' => false, 'code' => 'MS', 'name' => 'Montserrat'],
            ['enabled' => false, 'code' => 'MA', 'name' => 'Morocco'],
            ['enabled' => false, 'code' => 'MZ', 'name' => 'Mozambique'],
            ['enabled' => false, 'code' => 'MM', 'name' => 'Myanmar'],
            ['enabled' => false, 'code' => 'NA', 'name' => 'Namibia'],
            ['enabled' => false, 'code' => 'NR', 'name' => 'Nauru'],
            ['enabled' => false, 'code' => 'NP', 'name' => 'Nepal'],
            ['enabled' => false, 'code' => 'NC', 'name' => 'New Caledonia'],
            ['enabled' => false, 'code' => 'NI', 'name' => 'Nicaragua'],
            ['enabled' => false, 'code' => 'NE', 'name' => 'Niger'],
            ['enabled' => false, 'code' => 'NG', 'name' => 'Nigeria'],
            ['enabled' => false, 'code' => 'NU', 'name' => 'Niue'],
            ['enabled' => false, 'code' => 'NF', 'name' => 'Norfolk Island'],
            ['enabled' => false, 'code' => 'MP', 'name' => 'Northern Mariana Islands'],
            ['enabled' => false, 'code' => 'OM', 'name' => 'Oman'],
            ['enabled' => false, 'code' => 'PK', 'name' => 'Pakistan'],
            ['enabled' => false, 'code' => 'PW', 'name' => 'Palau'],
            ['enabled' => false, 'code' => 'PS', 'name' => 'Palestinian Territory, Occupied'],
            ['enabled' => false, 'code' => 'PA', 'name' => 'Panama'],
            ['enabled' => false, 'code' => 'PG', 'name' => 'Papua New Guinea'],
            ['enabled' => false, 'code' => 'PY', 'name' => 'Paraguay'],
            ['enabled' => false, 'code' => 'PE', 'name' => 'Peru'],
            ['enabled' => false, 'code' => 'PH', 'name' => 'Philippines'],
            ['enabled' => false, 'code' => 'PN', 'name' => 'Pitcairn'],
            ['enabled' => false, 'code' => 'PL', 'name' => 'Poland'],
            ['enabled' => false, 'code' => 'PR', 'name' => 'Puerto Rico'],
            ['enabled' => false, 'code' => 'QA', 'name' => 'Qatar'],
            ['enabled' => false, 'code' => 'RE', 'name' => 'Reunion'],
            ['enabled' => false, 'code' => 'RO', 'name' => 'Romania'],
            ['enabled' => false, 'code' => 'RW', 'name' => 'Rwanda'],
            ['enabled' => false, 'code' => 'BL', 'name' => 'Saint Barthélemy'],
            ['enabled' => false, 'code' => 'SH', 'name' => 'Saint Helena'],
            ['enabled' => false, 'code' => 'KN', 'name' => 'Saint Kitts and Nevis'],
            ['enabled' => false, 'code' => 'LC', 'name' => 'Saint Lucia'],
            ['enabled' => false, 'code' => 'MF', 'name' => 'Saint Martin (French part)'],
            ['enabled' => false, 'code' => 'PM', 'name' => 'Saint Pierre and Miquelon'],
            ['enabled' => false, 'code' => 'VC', 'name' => 'Saint Vincent and the Grenadines'],
            ['enabled' => false, 'code' => 'WS', 'name' => 'Samoa'],
            ['enabled' => false, 'code' => 'SM', 'name' => 'San Marino'],
            ['enabled' => false, 'code' => 'ST', 'name' => 'Sao Tome and Principe'],
            ['enabled' => false, 'code' => 'SA', 'name' => 'Saudi Arabia'],
            ['enabled' => false, 'code' => 'SN', 'name' => 'Senegal'],
            ['enabled' => false, 'code' => 'RS', 'name' => 'Serbia'],
            ['enabled' => false, 'code' => 'SC', 'name' => 'Seychelles'],
            ['enabled' => false, 'code' => 'SL', 'name' => 'Sierra Leone'],
            ['enabled' => false, 'code' => 'SG', 'name' => 'Singapore'],
            ['enabled' => false, 'code' => 'SX', 'name' => 'Sint Maarten (Dutch part)'],
            ['enabled' => false, 'code' => 'SK', 'name' => 'Slovakia'],
            ['enabled' => false, 'code' => 'SI', 'name' => 'Slovenia'],
            ['enabled' => false, 'code' => 'SB', 'name' => 'Solomon Islands'],
            ['enabled' => false, 'code' => 'SO', 'name' => 'Somalia'],
            ['enabled' => false, 'code' => 'ZA', 'name' => 'South Africa'],
            ['enabled' => false, 'code' => 'GS', 'name' => 'South Georgia and the South Sandwich Islands'],
            ['enabled' => false, 'code' => 'LK', 'name' => 'Sri Lanka'],
            ['enabled' => false, 'code' => 'SD', 'name' => 'Sudan'],
            ['enabled' => false, 'code' => 'SR', 'name' => 'Suriname'],
            ['enabled' => false, 'code' => 'SJ', 'name' => 'Svalbard and Jan Mayen'],
            ['enabled' => false, 'code' => 'SZ', 'name' => 'Swaziland'],
            ['enabled' => false, 'code' => 'SY', 'name' => 'Syrian Arab Republic'],
            ['enabled' => false, 'code' => 'TW', 'name' => 'Taiwan, Province of China'],
            ['enabled' => false, 'code' => 'TJ', 'name' => 'Tajikistan'],
            ['enabled' => false, 'code' => 'TZ', 'name' => 'Tanzania, United Republic of'],
            ['enabled' => false, 'code' => 'TH', 'name' => 'Thailand'],
            ['enabled' => false, 'code' => 'TL', 'name' => 'Timor-Leste'],
            ['enabled' => false, 'code' => 'TG', 'name' => 'Togo'],
            ['enabled' => false, 'code' => 'TK', 'name' => 'Tokelau'],
            ['enabled' => false, 'code' => 'TO', 'name' => 'Tonga'],
            ['enabled' => false, 'code' => 'TT', 'name' => 'Trinidad and Tobago'],
            ['enabled' => false, 'code' => 'TN', 'name' => 'Tunisia'],
            ['enabled' => false, 'code' => 'TR', 'name' => 'Turkey'],
            ['enabled' => false, 'code' => 'TM', 'name' => 'Turkmenistan'],
            ['enabled' => false, 'code' => 'TC', 'name' => 'Turks and Caicos Islands'],
            ['enabled' => false, 'code' => 'TV', 'name' => 'Tuvalu'],
            ['enabled' => false, 'code' => 'UG', 'name' => 'Uganda'],
            ['enabled' => false, 'code' => 'UA', 'name' => 'Ukraine'],
            ['enabled' => false, 'code' => 'AE', 'name' => 'United Arab Emirates'],
            ['enabled' => false, 'code' => 'UM', 'name' => 'United States Minor Outlying Islands'],
            ['enabled' => false, 'code' => 'UY', 'name' => 'Uruguay'],
            ['enabled' => false, 'code' => 'UZ', 'name' => 'Uzbekistan'],
            ['enabled' => false, 'code' => 'VU', 'name' => 'Vanuatu'],
            ['enabled' => false, 'code' => 'VE', 'name' => 'Venezuela, Bolivarian Republic of'],
            ['enabled' => false, 'code' => 'VN', 'name' => 'Viet Nam'],
            ['enabled' => false, 'code' => 'VG', 'name' => 'Virgin Islands, British'],
            ['enabled' => false, 'code' => 'VI', 'name' => 'Virgin Islands, U.S.'],
            ['enabled' => false, 'code' => 'WF', 'name' => 'Wallis and Futuna'],
            ['enabled' => false, 'code' => 'EH', 'name' => 'Western Sahara'],
            ['enabled' => false, 'code' => 'YE', 'name' => 'Yemen'],
            ['enabled' => false, 'code' => 'ZM', 'name' => 'Zambia'],
            ['enabled' => false, 'code' => 'ZW', 'name' => 'Zimbabwe'],
        ]);

        $us = Country::whereCode('US')->first();
        $us->states()->createMany([
            ['code' => 'AL', 'name' => 'Alabama'],
            ['code' => 'AK', 'name' => 'Alaska'],
            ['code' => 'AS', 'name' => 'American Samoa'],
            ['code' => 'AZ', 'name' => 'Arizona'],
            ['code' => 'AR', 'name' => 'Arkansas'],
            ['code' => 'CA', 'name' => 'California'],
            ['code' => 'CO', 'name' => 'Colorado'],
            ['code' => 'CT', 'name' => 'Connecticut'],
            ['code' => 'DE', 'name' => 'Delaware'],
            ['code' => 'DC', 'name' => 'Dist. of Columbia'],
            ['code' => 'FL', 'name' => 'Florida'],
            ['code' => 'GA', 'name' => 'Georgia'],
            ['code' => 'GU', 'name' => 'Guam'],
            ['code' => 'HI', 'name' => 'Hawaii'],
            ['code' => 'ID', 'name' => 'Idaho'],
            ['code' => 'IL', 'name' => 'Illinois'],
            ['code' => 'IN', 'name' => 'Indiana'],
            ['code' => 'IA', 'name' => 'Iowa'],
            ['code' => 'KS', 'name' => 'Kansas'],
            ['code' => 'KY', 'name' => 'Kentucky'],
            ['code' => 'LA', 'name' => 'Louisiana'],
            ['code' => 'ME', 'name' => 'Maine'],
            ['code' => 'MD', 'name' => 'Maryland'],
            ['code' => 'MH', 'name' => 'Marshall Islands'],
            ['code' => 'MA', 'name' => 'Massachusetts'],
            ['code' => 'MI', 'name' => 'Michigan'],
            ['code' => 'FM', 'name' => 'Micronesia'],
            ['code' => 'MN', 'name' => 'Minnesota'],
            ['code' => 'MS', 'name' => 'Mississippi'],
            ['code' => 'MO', 'name' => 'Missouri'],
            ['code' => 'MT', 'name' => 'Montana'],
            ['code' => 'NE', 'name' => 'Nebraska'],
            ['code' => 'NV', 'name' => 'Nevada'],
            ['code' => 'NH', 'name' => 'New Hampshire'],
            ['code' => 'NJ', 'name' => 'New Jersey'],
            ['code' => 'NM', 'name' => 'New Mexico'],
            ['code' => 'NY', 'name' => 'New York'],
            ['code' => 'NC', 'name' => 'North Carolina'],
            ['code' => 'ND', 'name' => 'North Dakota'],
            ['code' => 'MP', 'name' => 'Northern Marianas'],
            ['code' => 'OH', 'name' => 'Ohio'],
            ['code' => 'OK', 'name' => 'Oklahoma'],
            ['code' => 'OR', 'name' => 'Oregon'],
            ['code' => 'PW', 'name' => 'Palau'],
            ['code' => 'PA', 'name' => 'Pennsylvania'],
            ['code' => 'PR', 'name' => 'Puerto Rico'],
            ['code' => 'RI', 'name' => 'Rhode Island'],
            ['code' => 'SC', 'name' => 'South Carolina'],
            ['code' => 'SD', 'name' => 'South Dakota'],
            ['code' => 'TN', 'name' => 'Tennessee'],
            ['code' => 'TX', 'name' => 'Texas'],
            ['code' => 'UT', 'name' => 'Utah'],
            ['code' => 'VT', 'name' => 'Vermont'],
            ['code' => 'VA', 'name' => 'Virginia'],
            ['code' => 'VI', 'name' => 'Virgin Islands'],
            ['code' => 'WA', 'name' => 'Washington'],
            ['code' => 'WV', 'name' => 'West Virginia'],
            ['code' => 'WI', 'name' => 'Wisconsin'],
            ['code' => 'WY', 'name' => 'Wyoming'],
        ]);

        $ca = Country::whereCode('CA')->first();
        $ca->states()->createMany([
            ['code' => 'AB', 'name' => 'Alberta'],
            ['code' => 'BC', 'name' => 'British Columbia'],
            ['code' => 'MB', 'name' => 'Manitoba'],
            ['code' => 'NB', 'name' => 'New Brunswick'],
            ['code' => 'NL', 'name' => 'Newfoundland and Labrador'],
            ['code' => 'NT', 'name' => 'Northwest Territories'],
            ['code' => 'NS', 'name' => 'Nova Scotia'],
            ['code' => 'NU', 'name' => 'Nunavut'],
            ['code' => 'ON', 'name' => 'Ontario'],
            ['code' => 'PE', 'name' => 'Prince Edward Island'],
            ['code' => 'QC', 'name' => 'Quebec'],
            ['code' => 'SK', 'name' => 'Saskatchewan'],
            ['code' => 'YT', 'name' => 'Yukon'],
        ]);

        $au = Country::whereCode('AU')->first();
        $au->states()->createMany([
            ['code' => 'NSW', 'name' => 'New South Wales'],
            ['code' => 'QLD', 'name' => 'Queensland'],
            ['code' => 'SA', 'name' => 'South Australia'],
            ['code' => 'TAS', 'name' => 'Tasmania'],
            ['code' => 'VIC', 'name' => 'Victoria'],
            ['code' => 'WA', 'name' => 'Western Australia'],
            ['code' => 'NT', 'name' => 'Northern Territory'],
            ['code' => 'ACT', 'name' => 'Australian Capital Territory'],
        ]);

        $de = Country::whereCode('DE')->first();
        $de->states()->createMany([
            ['code' => 'BW', 'name' => 'Baden-Württemberg'],
            ['code' => 'BY', 'name' => 'Bavaria'],
            ['code' => 'BE', 'name' => 'Berlin'],
            ['code' => 'BB', 'name' => 'Brandenburg'],
            ['code' => 'HB', 'name' => 'Bremen'],
            ['code' => 'HH', 'name' => 'Hamburg'],
            ['code' => 'HE', 'name' => 'Hesse'],
            ['code' => 'MV', 'name' => 'Mecklenburg-Vorpommern'],
            ['code' => 'NI', 'name' => 'Lower Saxony'],
            ['code' => 'NW', 'name' => 'North Rhine-Westphalia'],
            ['code' => 'RP', 'name' => 'Rhineland-Palatinate'],
            ['code' => 'SL', 'name' => 'Saarland'],
            ['code' => 'SN', 'name' => 'Saxony'],
            ['code' => 'ST', 'name' => 'Saxony-Anhalt'],
            ['code' => 'SH', 'name' => 'Schleswig-Holstein'],
            ['code' => 'TH', 'name' => 'Thuringia'],
        ]);

        $ie = Country::whereCode('IE')->first();
        $ie->states()->createMany([
            ['code' => 'D', 'name' => 'Dublin'],
            ['code' => 'WW', 'name' => 'Wicklow'],
            ['code' => 'WX', 'name' => 'Wexford'],
            ['code' => 'CW', 'name' => 'Carlow'],
            ['code' => 'KE', 'name' => 'Kildare'],
            ['code' => 'MH', 'name' => 'Meath'],
            ['code' => 'LH', 'name' => 'Louth'],
            ['code' => 'MN', 'name' => 'Monaghan'],
            ['code' => 'CN', 'name' => 'Cavan'],
            ['code' => 'LD', 'name' => 'Longford'],
            ['code' => 'WH', 'name' => 'Westmeath'],
            ['code' => 'OY', 'name' => 'Offaly'],
            ['code' => 'LS', 'name' => 'Laois'],
            ['code' => 'KK', 'name' => 'Kilkenny'],
            ['code' => 'WD', 'name' => 'Waterford'],
            ['code' => 'C', 'name' => 'Cork'],
            ['code' => 'KY', 'name' => 'Kerry'],
            ['code' => 'LK', 'name' => 'Limerick'],
            ['code' => 'TN', 'name' => 'North Tipperary'],
            ['code' => 'TS', 'name' => 'South Tipperary'],
            ['code' => 'CE', 'name' => 'Clare'],
            ['code' => 'G', 'name' => 'Galway'],
            ['code' => 'MO', 'name' => 'Mayo'],
            ['code' => 'RN', 'name' => 'Roscommon'],
            ['code' => 'SO', 'name' => 'Sligo'],
            ['code' => 'LM', 'name' => 'Leitrim'],
            ['code' => 'DL', 'name' => 'Donegal'],
        ]);
        
        $nl = Country::whereCode('NL')->first();
        $nl->states()->createMany([
            ['code' => 'DR', 'name' => 'Drenthe'],
            ['code' => 'FL', 'name' => 'Flevoland'],
            ['code' => 'FR', 'name' => 'Friesland'],
            ['code' => 'GE', 'name' => 'Gelderland'],
            ['code' => 'GR', 'name' => 'Groningen'],
            ['code' => 'LI', 'name' => 'Limburg'],
            ['code' => 'NB', 'name' => 'Noord-Brabant'],
            ['code' => 'NH', 'name' => 'Noord-Holland'],
            ['code' => 'OV', 'name' => 'Overijssel'],
            ['code' => 'UT', 'name' => 'Utrecht'],
            ['code' => 'ZE', 'name' => 'Zeeland'],
            ['code' => 'ZH', 'name' => 'Zuid-Holland'],
        ]);

    }

}
