<?php namespace RainLab\User\Models;

use Event;
use Request;
use October\Rain\Database\ExpandoModel;

/**
 * UserLog Model
 *
 * @property int $user_id
 * @property string $type
 * @property array $data
 * @property array $comment
 * @property bool $is_comment is_comment flags this log item as a comment
 * @property bool $is_system is_system flags this log item as generated by an admin or system
 * @property int $updated_user_id
 * @property int $created_user_id
 * @property \Illuminate\Support\Carbon $updated_at
 * @property \Illuminate\Support\Carbon $created_at
 *
 * @package rainlab\user
 * @author Alexey Bobkov, Samuel Georges
 */
class UserLog extends ExpandoModel
{
    use \October\Rain\Database\Traits\Validation;
    use \October\Rain\Database\Traits\UserFootprints;
    use \RainLab\User\Models\UserLog\HasModelAttributes;

    const TYPE_NEW_USER = 'new-user';
    const TYPE_SET_EMAIL = 'set-email';
    const TYPE_SET_PASSWORD = 'set-password';
    const TYPE_SET_TWO_FACTOR = 'set-two-factor';
    const TYPE_SELF_VERIFY = 'self-verify';
    const TYPE_SELF_LOGIN = 'self-login';
    const TYPE_SELF_DELETE = 'self-delete';
    const TYPE_SELF_PASSWORD_RESET = 'self-password-reset';
    const TYPE_SELF_PASSWORD_CHANGE = 'self-password-change';
    const TYPE_ADMIN_IMPERSONATE = 'admin-impersonate';
    const TYPE_ADMIN_BAN = 'admin-ban';
    const TYPE_ADMIN_UNBAN = 'admin-unban';
    const TYPE_ADMIN_DELETE = 'admin-delete';
    const TYPE_ADMIN_RESTORE = 'admin-restore';
    const TYPE_ADMIN_CONVERT_GUEST = 'admin-convert-guest';
    const TYPE_ADMIN_MERGE = 'admin-merge';
    const TYPE_INTERNAL_COMMENT = 'internal-comment';

    /**
     * @var string table name
     */
    public $table = 'rainlab_user_user_logs';

    /**
     * @var array rules for validation
     */
    public $rules = [];

    /**
     * @var string expandoColumn name to store the data
     */
    protected $expandoColumn = 'data';

    /**
     * @var array expandoPassthru attributes that should not be serialized
     */
    protected $expandoPassthru = [
        'type',
        'comment',
        'is_comment',
        'is_system',
        'user_id',
    ];

    /**
     * @var array Relations
     */
    public $belongsTo = [
        'user' => [
            User::class,
            'scope' => 'withTrashed'
        ]
    ];

    /**
     * filterTypeOptions returns available type options for the list filter
     */
    public function filterTypeOptions()
    {
        $options = [
            self::TYPE_NEW_USER => __("New User"),
            self::TYPE_SELF_LOGIN => __("Login"),
            self::TYPE_SET_EMAIL => __("Email Changed"),
            self::TYPE_SET_PASSWORD => __("Password Changed"),
            self::TYPE_SELF_PASSWORD_CHANGE => __("Password Changed (Self)"),
            self::TYPE_SELF_PASSWORD_RESET => __("Password Reset"),
            self::TYPE_SET_TWO_FACTOR => __("Two-Factor Changed"),
            self::TYPE_SELF_VERIFY => __("Email Verified"),
            self::TYPE_SELF_DELETE => __("Account Deleted"),
            self::TYPE_ADMIN_IMPERSONATE => __("Impersonation"),
            self::TYPE_ADMIN_BAN => __("Banned"),
            self::TYPE_ADMIN_UNBAN => __("Unbanned"),
            self::TYPE_ADMIN_DELETE => __("Deleted by Admin"),
            self::TYPE_ADMIN_RESTORE => __("Restored by Admin"),
            self::TYPE_ADMIN_CONVERT_GUEST => __("Guest Converted"),
            self::TYPE_ADMIN_MERGE => __("User Merged"),
        ];

        $extended = Event::fire('rainlab.user.extendLogTypeOptions', [$this]);
        foreach ((array) $extended as $extra) {
            if (is_array($extra)) {
                $options += $extra;
            }
        }

        return $options;
    }

    /**
     * createRecord adds a log for a user
     */
    public static function createRecord($userId, $type, $data = [])
    {
        $data['ip_address'] = Request::ip();

        $obj = new static;
        $obj->user_id = $userId;
        $obj->type = $type;
        $obj->data = $data;
        $obj->is_comment = false;
        $obj->is_system = false;
        $obj->setExpandoAttributes($data);
        $obj->save();

        return $obj;
    }

    /**
     * createSystemRecord adds a log for a user, generated by an administrator
     */
    public static function createSystemRecord($userId, $type, $data = [])
    {
        $data['ip_address'] = Request::ip();

        $obj = new static;
        $obj->user_id = $userId;
        $obj->type = $type;
        $obj->data = $data;
        $obj->is_comment = false;
        $obj->is_system = true;
        $obj->setExpandoAttributes($data);
        $obj->save();

        return $obj;
    }

    /**
     * createSystemComment adds a comment log for a user, generated by an administrator
     */
    public static function createSystemComment($userId, $comment)
    {
        $data = [];
        $data['ip_address'] = Request::ip();

        $obj = new static;
        $obj->user_id = $userId;
        $obj->type = self::TYPE_INTERNAL_COMMENT;
        $obj->comment = $comment;
        $obj->is_comment = true;
        $obj->is_system = true;
        $obj->data = $data;
        $obj->save();

        return $obj;
    }
}
