# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: rainlab.user::lang.group.label

# Model Form Field configuration
form: $/rainlab/user/models/usergroup/fields.yaml

# Model Class name
modelClass: RainLab\User\Models\UserGroup

# Default redirect location
defaultRedirect: rainlab/user/usergroups

# Create page
create:
    title: rainlab.user::lang.groups.create_title
    redirect: rainlab/user/usergroups/update/:id
    redirectClose: rainlab/user/usergroups

# Update page
update:
    title: rainlab.user::lang.groups.update_title
    redirect: rainlab/user/usergroups
    redirectClose: rainlab/user/usergroups

# Preview page
preview:
    title: rainlab.user::lang.groups.update_title